import * as fs from 'fs';
import * as path from 'path';

export const TEMP_PR_DESCRIPTION_FILE_NAME = '.jira-smart-pr-description.tmp.md';
const PLACEHOLDER_TOKEN = '<PASTE_COPILOT_PR_DESCRIPTION_HERE>';

export function resolveTempPRDescriptionFile(cwd: string): string {
  return path.join(cwd, TEMP_PR_DESCRIPTION_FILE_NAME);
}

export function buildTempPRDescriptionTemplate(input: {
  sourceBranch: string;
  jiraKey?: string;
}): string {
  const lines: string[] = [];
  lines.push('# PR Description Draft');
  lines.push('');
  lines.push('Replace the placeholder below with the final PR description generated by Copilot Chat.');
  lines.push('This file will be used to create the Bitbucket pull request body.');
  lines.push('');
  if (input.jiraKey) {
    lines.push(`JIRA: ${input.jiraKey}`);
  }
  lines.push(`Source branch: ${input.sourceBranch}`);
  lines.push('');
  lines.push(PLACEHOLDER_TOKEN);
  lines.push('');
  return lines.join('\n');
}

export function writeTempPRDescriptionFile(cwd: string, content: string): { path: string; overwritten: boolean } {
  const filePath = resolveTempPRDescriptionFile(cwd);
  const overwritten = fs.existsSync(filePath);
  fs.writeFileSync(filePath, content, 'utf8');
  return { path: filePath, overwritten };
}

export function readTempPRDescriptionFile(cwd: string): { path: string; body: string } {
  const filePath = resolveTempPRDescriptionFile(cwd);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Temporary PR description file not found: ${TEMP_PR_DESCRIPTION_FILE_NAME}`);
  }

  const body = fs.readFileSync(filePath, 'utf8').trim();
  if (!body) {
    throw new Error(`Temporary PR description file is empty: ${TEMP_PR_DESCRIPTION_FILE_NAME}`);
  }
  if (body.includes(PLACEHOLDER_TOKEN)) {
    throw new Error(
      `Temporary PR description still contains placeholder content. Replace '${PLACEHOLDER_TOKEN}' with the final description first.`
    );
  }

  return { path: filePath, body };
}

export function deleteTempPRDescriptionFile(cwd: string): void {
  const filePath = resolveTempPRDescriptionFile(cwd);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}
